# Version information.
program_name:       "fractals"
program_ver:        0.1.0
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
# Fractals
fractals_folder:    "./my_fractals"
fractal_file:       "fractal_settings.toml"
hist_plot_log:      true

